### ISSUE TITLE
Add meta tags 

### ISSUE THREAD

**Issue by DevrajDC** [Design-and-Code/Design-and-Code#10]
Add all meta tags and change the react app name along with the favicon.

Resources:

- https://metatags.io/ - For generating meta tags.
- Change react app name to "Design and Code"
- Favicon: ![DC Logo](https://user-images.githubusercontent.com/65373279/136816537-20e6e2f3-d375-4607-85e0-c89c3749d020.png) 

If you need anything ping me on discord! https://discord.gg/druweDMn3s

**Comment by Alkaison** [comment]
I will be working on this. I will add the meta Tags.

**Comment by Alkaison** [comment]
- I have added many meta tags for better SEO: https://github.com/Design-and-Code/Design-and-Code/pull/72
