### ISSUE TITLE
[Bug]: "Join Us" button in the footer is not working

### ISSUE THREAD

**Issue by ShaileshKumar007** [Design-and-Code/Design-and-Code#16]
Join us button in the footer of the Home page is not working.
It should redirect us to the discord server of Design-and-Code when clicked, but it is doing nothing.

## Screenshot:
![join us](https://user-images.githubusercontent.com/71178959/137599374-d3cb33b4-6882-4cb9-9859-f5387135a96c.JPG)

**Comment by sidwebworks** [comment]
Closing this as resolved
