### ISSUE TITLE
Socials images in the footer is not working

### ISSUE THREAD

**Issue by ShaileshKumar007** [Design-and-Code/Design-and-Code#18]
The socials icons in the footer are not working.
While clicking on this, it should redirect us to the given social site of "Design and Code" but it is doing nothing.

## Screenshot:
![socials](https://user-images.githubusercontent.com/71178959/137599741-c9b34ab6-a4b1-44be-9c27-b02f72263690.JPG)

**Comment by sidwebworks** [comment]
Closing as resolved
