### ISSUE TITLE
Change Favicon for the website 

### ISSUE THREAD

**Issue by divyanshraj0408** [Design-and-Code/Design-and-Code#24]
### What is the problem?
The favicon for the [website](https://designandcode.netlify.app/) is still the default react favicon.
### What we can do?
We need to change the favicon to the desired favicon.
### How we can do it?
In the public folder we need to delete or edit the existing favicon.ico file to the desired logo with the same file name in the same directory.

Kindly assign this issue to me and please provide the icon which we need to use

**Comment by Shivansh-yadav13** [comment]
I would like to contribute 😊

**Comment by aayushchugh** [comment]
Well it's correct one now

![image](https://user-images.githubusercontent.com/69336518/187037796-51181d83-f297-4d13-ad5f-dba78d4f94c9.png)

**Comment by aayushchugh** [comment]
@sidwebworks Please close (if it's okay) this issue as it is already completed
