### ISSUE TITLE
Feat: Appear On Scroll UI

### ISSUE THREAD

**Issue by nawed2611** [Design-and-Code/Design-and-Code#40]
I believe Appear on Scroll animations would look attractive on the website and improve the UI

**Comment by DevrajDC** [comment]
Yes, we will be working on animations soon. Any animation library that you would like to recommend? @nawed2611

**Comment by nawed2611** [comment]
I think [Animate On Scroll](https://michalsnik.github.io/aos/) works best!

**Comment by DevrajDC** [comment]
Yes, i have used it many times before. Will go ahead with this! 🙌🏻

**Comment by nawed2611** [comment]
Can I start working on it?

**Comment by DevrajDC** [comment]
Yeah sure, go ahead!

**Comment by nawed2611** [comment]
I have submitted a PR #41. Kindly review!

**Comment by DevrajDC** [comment]
Hey, i had a quick view on the preview link and i need to have further discussion with you regarding the animations. Have you joined our discord community? If yes, feel free to add me as a friend on discord and we can communicate much better!

**Comment by nawed2611** [comment]
Sure!
