### ISSUE TITLE
There should be a loading indicator on image in about us page

### ISSUE THREAD

**Issue by aayushchugh** [Design-and-Code/Design-and-Code#65]
In about us page at `our community` section when this image is loading than there is just white space but there should be
some kind of loading indicator there 

![Recording 2022-09-23 at 16 03 01](https://user-images.githubusercontent.com/69336518/191942860-c2da034a-f253-4da0-83fe-521ca06ef0f5.gif)

**Comment by DevrajDC** [comment]
What do you think would look good?

**Comment by aayushchugh** [comment]
I can try this

**Comment by DevrajDC** [comment]
Sure, go ahead!

**Comment by DevrajDC** [comment]
![aboutIllustration 1](https://user-images.githubusercontent.com/65373279/191977457-142a10ec-8492-44e9-a590-6bdd893aaeb2.png)

Hey @aayushchugh, here you go!

**Comment by DevrajDC** [comment]
let me know if you need any other format, like svg, png, jpeg, webp etc

**Comment by aayushchugh** [comment]
is this svg?

I need svg only

**Comment by DevrajDC** [comment]
![aboutIllustration 1](https://user-images.githubusercontent.com/65373279/191977908-d807c38c-3d63-4f64-b7b4-b3989fefda78.svg)
Here is the svg export

**Comment by aayushchugh** [comment]
Thanks, I will work on this now

**Comment by DevrajDC** [comment]
Awesome, keep me posted!
