### ISSUE TITLE
Fix button size

### ISSUE THREAD

**Issue by priyankarpal** [Design-and-Code/Design-and-Code#73]
* need to fix the "Join Discord" button's width & height
* Also need to fix the partnership button. 

![image](https://user-images.githubusercontent.com/88102392/221934927-733cd4b2-288a-46c8-bd0f-bca6ada97883.png)

* Add CONTRIBUTING.md file

**Comment by Panquesito7** [comment]
For the contributing file, you should create an issue for it.

**Comment by JOSHI-owo** [comment]
Is this issue still there? I think the problem with the "Join Discord" button width and height has been resolved.
