### ISSUE TITLE
Plus Icon is not visible in footer section

### ISSUE THREAD

**Issue by mishra-nikhil0110** [Design-and-Code/Design-and-Code#80]
![Screenshot (12)](https://github.com/Design-and-Code/Design-and-Code/assets/105505070/19b8cb25-0280-46a1-8c7a-d0d39005ae51)

**Comment by Panquesito7** [comment]
Looks like it's there, but it probably should use another color.
Would you like to work on this? 🙂

**Comment by mishra-nikhil0110** [comment]
sure, please assign me this.
